
name: Sign MSIX with Azure Trusted Signing

on:
  push:
    branches:
      - main

jobs:
  sign-msi:
    runs-on: ubuntu-latest  # <-- Change this to Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      
