
name: Sign MSIX with Azure Trusted Signing

on:
  push:
    branches:
      - main

jobs:
  sign-msi:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      
      
      
      
      - name: Upload MSI to SFTP Server (Port 22)
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 22
          source: "${{ github.workspace }}/PDMCLI.msix"
          target: "/home/S8bt11tCw6zWQ7/html/wp-content/pdmshell_test/pdmcliSigned.msix"
      

