
name: Sign MSIX with Azure Trusted Signing

on:
  push:
    branches:
      - main

jobs:
  sign-msi:
    runs-on: ubuntu-latest  # <-- Change this to Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Get Commit Message (Version Number)
        id: get_version
        run: echo "VERSION=$(git log -1 --pretty=%B)" >> $GITHUB_ENV
  
      - name: Create Version Folder on SFTP (Using SSH)
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 22
          script: |
            mkdir -p /home/S8bt11tCw6zWQ7/html/wp-content/pdmshell_test/${{ env.VERSION }}
            ls -ld /home/S8bt11tCw6zWQ7/html/wp-content/pdmshell_test/${{ env.VERSION }}  # Verify folder creation
            
      - name: Deploy with Password
        uses: wlixcc/SFTP-Deploy-Action@v1.2.5
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          server: ${{ secrets.SFTP_HOST }}
          port: 22
          password: ${{ secrets.SFTP_PASSWORD }}
          local_path: "./PDMCLI.msix"
          remote_path: "/home/S8bt11tCw6zWQ7/html/wp-content/pdmshell_test/${{ env.VERSION }}"
          sftp_only: true
          sftpArgs: "-vvv"  # Enable verbose debugging output
          
      - name: Download version.txt from SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.5
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          server: ${{ secrets.SFTP_HOST }}
          port: 22
          password: ${{ secrets.SFTP_PASSWORD }}
          local_path: "./version.txt"
          remote_path: "/home/S8bt11tCw6zWQ7/html/wp-content/pdmshell_test/version.txt"
          sftp_only: true
          sftpArgs: "-vvv"
      
      - name: Append New Version to version.txt
        run: |
          echo "${{ env.VERSION }}" >> version.txt
          cat version.txt  # Debugging step to verify contents
      
      - name: Upload Updated version.txt to SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.5
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          server: ${{ secrets.SFTP_HOST }}
          port: 22
          password: ${{ secrets.SFTP_PASSWORD }}
          local_path: "./version.txt"
          remote_path: "/home/S8bt11tCw6zWQ7/html/wp-content/pdmshell_test/version.txt"
          sftp_only: true
          sftpArgs: "-vvv"
