
name: Sign MSIX with Azure Trusted Signing

on:
  push:
    branches:
      - main

jobs:
  sign-msi:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get Commit Message (Version Number)
        id: get_version
        run: echo "VERSION=$(git log -1 --pretty=%B)" >> $GITHUB_ENV
        
      - name: List files in the workspace (for debugging)
        run: Get-ChildItem -Path ${{ github.workspace }} -Recurse
      
      
      
      - name: Create Signing Catalog file
        run: |
           echo "PDMCLI.msix" > catalog.txt  # Replace with your MSI filename

      - name: Sign MSIX using Azure Trusted Signing
        uses: azure/trusted-signing-action@v0.3.16
        with:
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          endpoint: https://wus2.codesigning.azure.net/  # Change if using a different region
          code-signing-account-name: BLUE-BYTE-SYSTEMS-INC
          certificate-profile-name: certificate
          files-catalog: ${{ github.workspace }}\catalog.txt
          file-digest: SHA256
          timestamp-rfc3161: http://timestamp.acs.microsoft.com
          timestamp-digest: SHA256

      - name: Verify Signature (PowerShell)
        run: |
          Get-AuthenticodeSignature -FilePath "PDMCLI.msix"

      - name: Upload Signed MSIX as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: signed-msix
          path: "${{ github.workspace }}/pdmcliSigned.msix"
      - name: Upload MSI to SFTP Server (Port 22)
        uses: actions/sshpass@v1
        with:
          command: |
            sshpass -p "${{ secrets.SFTP_PASSWORD }}" sftp -P 22 -o StrictHostKeyChecking=no ${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_HOST }} <<EOF
            mkdir -p /home/S8bt11tCw6zWQ7/html/wp-content/pdmshell_test/${{ env.VERSION }}
            put ${{ github.workspace }}/pdmcliSigned.msix /home/S8bt11tCw6zWQ7/html/wp-content/pdmshell_test/${{ env.VERSION }}/pdmcliSigned.msix
            EOF

