
name: Sign MSIX with Azure Trusted Signing

on:
  push:
    branches:
      - main

jobs:
  sign-msi:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      
      
      
      - name: Upload MSI to SFTP Server using psftp (Windows)
        shell: powershell
        run: |
          echo "open ${{ secrets.SFTP_HOST }} 22" > sftp_script.txt
          echo "user ${{ secrets.SFTP_USERNAME }} ${{ secrets.SFTP_PASSWORD }}" >> sftp_script.txt
          echo "mkdir /home/S8bt11tCw6zWQ7/html/wp-content/pdmshell_test" >> sftp_script.txt
          echo "cd /home/S8bt11tCw6zWQ7/html/wp-content/pdmshell_test" >> sftp_script.txt
          echo "put ${{ github.workspace }}/PDMCLI.msix" >> sftp_script.txt
          echo "bye" >> sftp_script.txt
          & "C:\Program Files\PuTTY\psftp.exe" -b sftp_script.txt
      

