
name: Sign MSIX with Azure Trusted Signing

on:
  push:
    branches:
      - main

jobs:
  sign-msi:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      
      
      
      
      
      - name: Upload MSI to SFTP Server (Port 22)
        uses: actions/sshpass@v1
        with:
          command: |
            sshpass -p "${{ secrets.SFTP_PASSWORD }}" sftp -P 22 -o StrictHostKeyChecking=no ${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_HOST }} <<EOF
            mkdir -p /home/S8bt11tCw6zWQ7/html/wp-content/pdmshell_test/${{ env.VERSION }}
            put "PDMCLI.msix" /home/S8bt11tCw6zWQ7/html/wp-content/pdmshell_test/${{ env.VERSION }}/pdmcliSigned.msix
            EOF

