
name: Sign MSIX with Azure Trusted Signing

on:
  push:
    branches:
      - main

jobs:
  sign-msi:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Check
        shell: powershell
        run: |
          if (!(Test-Path "C:\Program Files (x86)\WinSCP\winscp.com")) {
            echo "ERROR: psftp.exe not found!"
            exit 1
          } else {
            echo "PuTTY psftp.exe found!"
          }
      
      - name: Upload MSI to SFTP Server using WinSCP
        shell: powershell
        run: |
          $WinSCPscript = @"
          open sftp://${{ secrets.SFTP_USERNAME }}:${{ secrets.SFTP_PASSWORD }}@${{ secrets.SFTP_HOST }} -hostkey=*
          mkdir /home/S8bt11tCw6zWQ7/html/wp-content/pdmshell_test
          put ${{ github.workspace }}\PDMCLI.msix /home/S8bt11tCw6zWQ7/html/wp-content/pdmshell_test/PDMCLI.msix
          exit
          "@
          $WinSCPscript | Out-File -FilePath "winscp-script.txt"
          Start-Process -FilePath "C:\Program Files (x86)\WinSCP\winscp.com" -ArgumentList "/script=winscp-script.txt" -NoNewWindow -Wait
      
      

