
name: Sign MSIX with Azure Trusted Signing

on:
  push:
    branches:
      - main

jobs:
  sign-msi:
    runs-on: ubuntu-latest  # <-- Change this to Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Get Commit Message (Version Number)
        id: get_version
        run: echo "VERSION=$(git log -1 --pretty=%B)" >> $GITHUB_ENV
  
      
