name: Upload Signed MSI to SFTP

on:
  workflow_run:
    workflows: ["Sign MSI with Azure Trusted Signing"]
    types:
      - completed

jobs:
  sign-msi:
    runs-on: ubuntu-latest  # <-- Change this to Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Get Commit Message (Version Number)
        id: get_version
        run: echo "VERSION=$(git log -1 --pretty=%B)" >> $GITHUB_ENV
  
      - name: Create Version Folder on SFTP (Using SSH)
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 22
          script: |
            mkdir -p /home/S8bt11tCw6zWQ7/html/wp-content/pdmshell_test/${{ env.VERSION }}
            ls -ld /home/S8bt11tCw6zWQ7/html/wp-content/pdmshell_test/${{ env.VERSION }}  # Verify folder creation
            
      - name: Upload MSI To SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.5
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          server: ${{ secrets.SFTP_HOST }}
          port: 22
          password: ${{ secrets.SFTP_PASSWORD }}
          local_path: "./PDMCLI.msix"
          remote_path: "/home/S8bt11tCw6zWQ7/html/wp-content/pdmshell_test/${{ env.VERSION }}"
          sftp_only: true
          sftpArgs: "-vvv"  # Enable verbose debugging output
          
      - name: Retrieve version.txt from SFTP (using SSH)
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 22
          script: |
            FILE="/home/***/html/wp-content/pdmshell_test/version.txt"
            echo "Checking if version.txt exists..."
            ls -lah /home/S8bt11tCw6zWQ7/html/wp-content/pdmshell_test/  # List directory contents
            if [ ! -f "$FILE" ]; then
              echo "Creating version.txt as it does not exist."
              touch "$FILE"
            fi
            echo "Copying version.txt to local workspace..."
            cat "$FILE" > version.txt
      - name: Download version.txt from SFTP (using SFTP)
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 22
          script: |
            FILE="/home/S8bt11tCw6zWQ7/html/wp-content/pdmshell_test/version.txt"
            if [ -f "$FILE" ]; then
              echo "Downloading version.txt"
              cat "$FILE"
            else
              echo "version.txt does not exist!"
            fi
      - name: Verify version.txt exists
        run: |
          echo "Checking if version.txt was downloaded..."
          ls -lah
          cat version.txt || echo "version.txt not found!"

       # Step 2: Debugging - Show contents of version.txt after downloading
      - name: Display contents of downloaded version.txt
        run: |
          echo "=== Contents of downloaded version.txt ==="
          cat version.txt
          echo "========================================"
          
      - name: Append New Version to version.txt
        run: |
          echo "${{ env.VERSION }}" >> version.txt
          cat version.txt  # Debugging step to verify contents

      - name: Display contents of Upload version.txt
        run: |
          echo "=== Contents of downloaded version.txt ==="
          cat version.txt
          echo "========================================"
          
      - name: Upload Updated version.txt to SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.5
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          server: ${{ secrets.SFTP_HOST }}
          port: 22
          password: ${{ secrets.SFTP_PASSWORD }}
          local_path: "./version.txt"
          remote_path: "/home/S8bt11tCw6zWQ7/html/wp-content/pdmshell_test/version.txt"
          sftp_only: true
          sftpArgs: "-vvv"
