name: Upload Signed MSI to SFTP

on:
  workflow_run:
    workflows: ["Sign MSI with Azure Trusted Signing"]
    types:
      - completed

jobs:
  upload-msi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get Commit Message (Version Number)
        id: get_version
        run: echo "VERSION=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

      - name: Deploy MSI to SFTP Server (Versioned Folder)
        uses: wlixcc/SFTP-Deploy-Action@v1.2.5
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          server: ${{ secrets.SFTP_HOST }}
          port: 22
          password: ${{ secrets.SFTP_PASSWORD }}
          local_path: "./pdmcli.msi"
          remote_path: "/home/S8bt11tCw6zWQ7/html/wp-content/pdmshell_test/2.4"
          sftp_only: true
          sftpArgs: "-vvv"

      - name: Download version.txt from SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.5
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          server: ${{ secrets.SFTP_HOST }}
          port: 22
          password: ${{ secrets.SFTP_PASSWORD }}
          local_path: "./version.txt"
          remote_path: "/home/S8bt11tCw6zWQ7/html/wp-content/pdmshell_test/version.txt"
          sftp_only: true
          sftpArgs: "-vvv"
      
      - name: Append New Version to version.txt
        run: |
          echo "${{ env.VERSION }}" >> version.txt
          cat version.txt  # Debugging step to verify contents
      
      - name: Upload Updated version.txt to SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.5
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          server: ${{ secrets.SFTP_HOST }}
          port: 22
          password: ${{ secrets.SFTP_PASSWORD }}
          local_path: "./version.txt"
          remote_path: "/home/S8bt11tCw6zWQ7/html/wp-content/pdmshell_test/version.txt"
          sftp_only: true
          sftpArgs: "-vvv"
